### ISSUE TITLE
미믹 등급 오류 (미믹 상세 페이지와 마이 페이지의 등급 불일치)

### ISSUE THREAD

**Issue by jangjiyu** [hanghae99-s8realweek-E3/frontend#237]
[ 상세 페이지 ]
![Image](https://user-images.githubusercontent.com/102751923/193321171-3fa13108-df6f-4a39-a31e-7ee886fa18ce.png)

[ 마이 페이지 ]
![Image](https://user-images.githubusercontent.com/102751923/193321182-e322ddff-daa2-44cf-b097-69fc7e516fc3.png)

-> 상세 페이지에 오류가 있는 것으로 보임

**Comment by DrunkenNeoguri** [comment]
수정 완료됐으면 닫아주세요.
