### ISSUE TITLE
비밀번호 길이 초과로 계정 탈퇴를 진행할 수 없음

### ISSUE THREAD

**Issue by piquark6046** [hanghae99-s8realweek-E3/frontend#239]
비밀번호 구성 방식: [KeePassXC](https://keepassxc.org/)에서 `[A-Z0-9]{30}` 조합으로 설정.

<details>
<summary>Screenshots</summary>

![Screenshot from 2022-09-30 18-40-49](https://user-images.githubusercontent.com/98787049/193336098-08e3b0cc-b023-44c7-ae7a-dd3d07b00c88.png)
![Screenshot from 2022-09-30 18-41-07](https://user-images.githubusercontent.com/98787049/193336108-a01c87bf-99a4-4670-ba8f-85450a71b62f.png)

</details>

**Comment by DrunkenNeoguri** [comment]
@piquark6046
안녕하세요! 소중한 이슈 남겨주셔서 감사합니다 :D
저희가 아직 이런 개념이 생소해서 조심스레 여쭤봅니다!
해쉬로 바꾼다라고 하시면 해당 사항을 프론트에서 해쉬 처리를 하고 보내는 것을 말씀하시는 것인지,
혹은 백엔드 쪽에서 관련 처리를 진행하시는 것인지,
혹은 저희가 잘못 생각하고 있다면 이부분이 생소해서 어느 부분에서 hash를 처리하면 될지..
추가 댓글로 알려주시면 참고해서 수정하도록 하겠습니다ㅠㅠ

**Comment by piquark6046** [comment]
https://github.com/hanghae99-s8realweek-E3/frontend/issues/239#issuecomment-1263946433
프론트엔드, 백엔드 둘다요.
프론트엔드는 사용자가 입력한 비밀번호를 hash(SHA-256 이상)로 변환하여 서버로 전송하고,
백엔드는 그 hash를 데이터베이스에 저장&검증하는 방식으로 하면 좋을 것 같아요.

근데, 어짜피 그게 개인정보 보호 목적으로 대한민국 정부 정책으로 이미 그렇게 하라고 해서요.
https://www.pipc.go.kr/np/cop/bbs/selectBoardArticle.do?bbsId=BS217&mCode=D010030000&nttId=7041#LINK

**Comment by DrunkenNeoguri** [comment]
@piquark6046
앗, 그렇군요! 내일 팀원들과 논의해서 수정할 수 있도록 하겠습니다!
소중한 의견 및 참고 자료 정말로 감사합니다!ㅠㅠㅠㅠ

**Comment by DrunkenNeoguri** [comment]
이슈 관련 논의 결과, 현재 https로 전달하고 있는 과정에서 문제가 없다고 판단하여 버그가 아닌 일반 이슈로 변경하여 일감을 닫도록 하겠습니다. (구글 등의 사이트에서도 평문으로 전달하고 있다는 내용들을 받아 해당 사항은 버그에서 제외하도록 하겠습니다.)
