### ISSUE TITLE
회원탈퇴 시 비밀번호가 20자를 초과하여 입력 가능한 문제

### ISSUE THREAD

**Issue by jangjiyu** [hanghae99-s8realweek-E3/frontend#240]
![Image](https://user-images.githubusercontent.com/102751923/193354380-a6634d82-8793-423a-aa67-acf5e6dbe40d.png)

20자까지만 작성 가능하게 해두는 게 좋을 듯합니다

**Comment by piquark6046** [comment]
근데, 어짜피 hash화하면 텍스트 길이는 상관없는데요.

**Comment by DrunkenNeoguri** [comment]
@piquark6046 저희 비밀번호 입력 길이가 20자 이내인데 넘어가서 발생하는 이슈입니다^^;

**Comment by jangjiyu** [comment]
![image](https://user-images.githubusercontent.com/102751923/193451402-4162ad3e-ed13-4b42-a0c5-72752cd4b3a5.png)

이거 20글자 넘게 입력 안 되게 막아줄 수 없나여

**Comment by DrunkenNeoguri** [comment]
아직 배포에 안넣었고 브랜치엔 적용된 상태입니다...
배포 올릴게유~
