### ISSUE TITLE
프론트엔드 CSS 이슈 모음

### ISSUE THREAD

**Issue by DrunkenNeoguri** [hanghae99-s8realweek-E3/frontend#95]
2022년 9월 20일부터 테스트 진행하면서 발생하는 프론트엔드 CSS 관련 이슈들을 해당 페이지에 정리합니다.
기능적인 이슈는 모음으로 생성하지 마시고, 하나의 카드로 생성해 관리할 수 있게 해주십시오.

미믹 페이지
- [x] 내가 만든 미믹 ->두줄 맞춤

회원가입 페이지
- [x] 커서포인터 잘넣기
- [x] 인풋창위에 글자 폰트?? 
- [x] 회원가입 버튼 글자 css
- [x] 첫 가입했을때 MBTI 선택창 라인이 이상함

디테일 페이지
- [x] 위에 이미지 안나오고있음
- [x] 이미지 사이즈
- [x] 도전할래요 버튼 마진값
- [x] 댓글 작성 margin-bottom 및 이미지 추가?
- [x] 상세피드페이지 상단 이미지 로고 깨짐
- [x] 팔로우 부분 배경이랑 색깔 다름

MBTI 피드 선택 페이지
- [] 색상이 다른 이유는 무엇인가요? 외의 영역에서 커서포인터가 들어가있음

**Comment by rlaedous** [comment]
미믹 페이지
1.내가 만든 미믹 ->두줄 맞춤

회원가입 페이지
1.커서포인터 잘넣기
2.인풋창위에 글자 폰트?? 
3.회원가입 버튼 글자 css

디테일 페이지
1.위에 이미지 안나오고있음
2.이미지 사이즈
3.도전할래요 버튼 마진값
4.댓글 작성 margin-bottom 및 이미지 추가?
